application: widgetsrv
version: 1
runtime: go
api_version: 3

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /widgets
  static_dir: widgets

- url: /.*
  script: _go_app